const initialProperties = [
  {
    id: 1,
    name: "Sunrise Apartments",
    address: "123 Main St, Cityville",
    units: [
      {
        id: "unit-1-1",
        unitNumber: "101",
        unitType: "Apartment",
        floorNumber: 1,
        area: 1200,
        occupancyStatus: "Occupied",
        tenant: { name: "Ravi Kumar", contact: "ravi.kumar@email.com" },
        rooms: { bedrooms: 2, bathrooms: 2, livingRooms: 1 },
        image: "/assets/units/sunrise-101.jpg",
      },
      {
        id: "unit-1-2",
        unitNumber: "102",
        unitType: "Apartment",
        floorNumber: 1,
        area: 1100,
        occupancyStatus: "Vacant",
        tenant: null,
        rooms: { bedrooms: 2, bathrooms: 1, livingRooms: 1 },
        image: "/assets/units/sunrise-102.jpg",
      },
      {
        id: "unit-1-3",
        unitNumber: "201",
        unitType: "Apartment",
        floorNumber: 2,
        area: 1300,
        occupancyStatus: "Occupied",
        tenant: { name: "Anjali Sharma", contact: "anjali.sharma@email.com" },
        rooms: { bedrooms: 3, bathrooms: 2, livingRooms: 1 },
        image: "/assets/units/sunrise-201.jpg",
      },
    ],
  },
  {
    id: 2,
    name: "Palm Residency",
    address: "456 Palm Ave, Townsville",
    units: [
      {
        id: "unit-2-1",
        unitNumber: "A1",
        unitType: "Apartment",
        floorNumber: 1,
        area: 1500,
        occupancyStatus: "Occupied",
        tenant: { name: "Priya Menon", contact: "priya.menon@email.com" },
        rooms: { bedrooms: 3, bathrooms: 2, livingRooms: 1 },
        image: "/assets/units/palm-a1.jpg",
      },
      {
        id: "unit-2-2",
        unitNumber: "A2",
        unitType: "Apartment",
        floorNumber: 1,
        area: 1400,
        occupancyStatus: "Vacant",
        tenant: null,
        rooms: { bedrooms: 2, bathrooms: 2, livingRooms: 1 },
        image: "/assets/units/palm-a2.jpg",
      },
      {
        id: "unit-2-3",
        unitNumber: "B1",
        unitType: "Apartment",
        floorNumber: 2,
        area: 1600,
        occupancyStatus: "Occupied",
        tenant: { name: "Amit Patel", contact: "amit.patel@email.com" },
        rooms: { bedrooms: 3, bathrooms: 3, livingRooms: 1 },
        image: "/assets/units/palm-b1.jpg",
      },
    ],
  },
  { id: 3, name: "Sky Towers", address: "789 Sky Rd, Metro City", units: [] },
  { id: 4, name: "Ocean View", address: "101 Ocean Dr, Beachside", units: [] },
  {
    id: 5,
    name: "Green Heights",
    address: "202 Green Ln, Hilltown",
    units: [
      {
        id: "unit-5-1",
        unitNumber: "G1",
        unitType: "Apartment",
        floorNumber: 1,
        area: 1250,
        occupancyStatus: "Vacant",
        tenant: null,
        rooms: { bedrooms: 2, bathrooms: 1, livingRooms: 1 },
        image: "/assets/units/green-g1.jpg",
      },
      {
        id: "unit-5-2",
        unitNumber: "G2",
        unitType: "Apartment",
        floorNumber: 1,
        area: 1350,
        occupancyStatus: "Occupied",
        tenant: { name: "Sonia Gupta", contact: "sonia.gupta@email.com" },
        rooms: { bedrooms: 3, bathrooms: 2, livingRooms: 1 },
        image: "/assets/units/green-g2.jpg",
      },
      {
        id: "unit-5-3",
        unitNumber: "H1",
        unitType: "Apartment",
        floorNumber: 2,
        area: 1450,
        occupancyStatus: "Vacant",
        tenant: null,
        rooms: { bedrooms: 2, bathrooms: 2, livingRooms: 1 },
        image: "/assets/units/green-h1.jpg",
      },
    ],
  },
  {
    id: 6,
    name: "Lakefront Villa",
    address: "303 Lake St, Lakeside",
    units: [
      {
        id: "unit-6-1",
        unitNumber: "V1",
        unitType: "Villa",
        floorNumber: 1,
        area: 2000,
        occupancyStatus: "Occupied",
        tenant: { name: "Vikram Singh", contact: "vikram.singh@email.com" },
        rooms: { bedrooms: 4, bathrooms: 3, livingRooms: 2 },
        image: "/assets/units/lakefront-v1.jpg",
      },
      {
        id: "unit-6-2",
        unitNumber: "V2",
        unitType: "Villa",
        floorNumber: 1,
        area: 2100,
        occupancyStatus: "Vacant",
        tenant: null,
        rooms: { bedrooms: 4, bathrooms: 3, livingRooms: 2 },
        image: "/assets/units/lakefront-v2.jpg",
      },
      {
        id: "unit-6-3",
        unitNumber: "V3",
        unitType: "Villa",
        floorNumber: 1,
        area: 2200,
        occupancyStatus: "Occupied",
        tenant: { name: "Neha Kapoor", contact: "neha.kapoor@email.com" },
        rooms: { bedrooms: 5, bathrooms: 4, livingRooms: 2 },
        image: "/assets/units/lakefront-v3.jpg",
      },
    ],
  },
  {
    id: 7,
    name: "Mountain Edge",
    address: "404 Mountain Rd, Peaksville",
    units: [],
  },
  { id: 8, name: "City Lights", address: "505 Light Ave, Downtown", units: [] },
];

export default initialProperties;