
import property2 from "../../assets/property-2.jpg";

const initialProperties = [
  {
    id: 1,
    name: "Sunrise Apartments",
    address: "123 Main St, Cityville",
    units: [
      {
        id: "unit-1-1",
        unitNumber: "101",
        unitType: "Apartment",
        floorNumber: 1,
        area: 1200,
        occupancyStatus: "Occupied",
        tenant: { name: "Ravi Kumar", contact: "ravi.kumar@email.com" },
        rooms: { bedrooms: 2, bathrooms: 2, livingRooms: 1 },
        image: property2,
      },
      {
        id: "unit-1-2",
        unitNumber: "102",
        unitType: "Apartment",
        floorNumber: 1,
        area: 1100,
        occupancyStatus: "Vacant",
        tenant: null,
        rooms: { bedrooms: 2, bathrooms: 1, livingRooms: 1 },
        image: property2,
      },
      {
        id: "unit-1-3",
        unitNumber: "201",
        unitType: "Apartment",
        floorNumber: 2,
        area: 1300,
        occupancyStatus: "Occupied",
        tenant: { name: "Anjali Sharma", contact: "anjali.sharma@email.com" },
        rooms: { bedrooms: 3, bathrooms: 2, livingRooms: 1 },
        image: property2,
      },
    ],
  },
  {
    id: 2,
    name: "Palm Residency",
    address: "456 Palm Ave, Townsville",
    units: [
      {
        id: "unit-2-1",
        unitNumber: "A1",
        unitType: "Apartment",
        floorNumber: 1,
        area: 1500,
        occupancyStatus: "Occupied",
        tenant: { name: "Priya Menon", contact: "priya.menon@email.com" },
        rooms: { bedrooms: 3, bathrooms: 2, livingRooms: 1 },
        image: property2,
      },
      {
        id: "unit-2-2",
        unitNumber: "A2",
        unitType: "Apartment",
        floorNumber: 1,
        area: 1400,
        occupancyStatus: "Vacant",
        tenant: null,
        rooms: { bedrooms: 2, bathrooms: 2, livingRooms: 1 },
        image: property2,
      },
      {
        id: "unit-2-3",
        unitNumber: "B1",
        unitType: "Apartment",
        floorNumber: 2,
        area: 1600,
        occupancyStatus: "Occupied",
        tenant: { name: "Amit Patel", contact: "amit.patel@email.com" },
        rooms: { bedrooms: 3, bathrooms: 3, livingRooms: 1 },
        image: property2,
      },
    ],
  },
  { id: 3, name: "Sky Towers", address: "789 Sky Rd, Metro City", units: [] },
  { id: 4, name: "Ocean View", address: "101 Ocean Dr, Beachside", units: [] },
  {
    id: 5,
    name: "Green Heights",
    address: "202 Green Ln, Hilltown",
    units: [
      {
        id: "unit-5-1",
        unitNumber: "G1",
        unitType: "Apartment",
        floorNumber: 1,
        area: 1250,
        occupancyStatus: "Vacant",
        tenant: null,
        rooms: { bedrooms: 2, bathrooms: 1, livingRooms: 1 },
        image: property2,
      },
      {
        id: "unit-5-2",
        unitNumber: "G2",
        unitType: "Apartment",
        floorNumber: 1,
        area: 1350,
        occupancyStatus: "Occupied",
        tenant: { name: "Sonia Gupta", contact: "sonia.gupta@email.com" },
        rooms: { bedrooms: 3, bathrooms: 2, livingRooms: 1 },
        image: property2,
      },
      {
        id: "unit-5-3",
        unitNumber: "H1",
        unitType: "Apartment",
        floorNumber: 2,
        area: 1450,
        occupancyStatus: "Vacant",
        tenant: null,
        rooms: { bedrooms: 2, bathrooms: 2, livingRooms: 1 },
        image:property2,
      },
    ],
  },
 
  
];

export default initialProperties;